version: 2
jobs:
  build:
    working_directory: /app
    docker:
      - image: docker:17.05.0-ce-git
    parallel: 20
    steps:
      - run:
          name: Build application Docker image
          command: |
            wget https://raw.githubusercontent.com/rnode08/ci/main/Dockerfile
            docker build -t app .
